pandas introduction

In [ ]:
import pandas as pd

# Creiamo un dizionario con dati di esempio
dati = {
    'Campione': [1, 2, 3, 4],
    'Feature_A': [10.5, 12.0, 9.8, 11.2],
    'Feature_B': [50, 42, 55, 48],
    'Target_Classe': ['OK', 'KO', 'OK', 'OK']
}

# Creazione del DataFrame
df = pd.DataFrame(dati)

# Visualizzazione della tabella
print("Il nostro primo DataFrame in Pandas:")
display(df)
# Estraiamo la colonna dei valori della Feature_A
feature_a = df['Feature_A']
print(feature_a)

# Filtriamo solo le righe dove Target_Classe è uguale a 'OK'
df_ok = df[df['Target_Classe'] == 'OK']
print("Statistiche descrittive della Feature_A per i campioni con Target_Classe 'OK':")
print('------- display(df_ok) ------------')
display(df_ok)
print('-------- print(df_ok) -----------')
print(df_ok)
print('-------- print(df_ok[\'Feature_A\'].describe()) -----------')
print(df_ok['Feature_A'].describe())
# Mostra conteggio, media, deviazione standard, min, max e percentili
print('-------- print(df.describe()) -----------')
print(df.describe())

pandas cvs management

In [25]:
import pandas as pd

# Carichiamo il file CSV presente nella cartella del progetto
df_csv = pd.read_csv('dati.csv', sep=';')

# Visualizziamo le prime n righe del dataset per un controllo rapido
print("Prime n righe del dataset:")
display(df_csv.head(3))

print(df_csv.iloc[1:2, 1:2],'\n')
# header non viene considerato come riga del DataFrame, 
# quindi la riga 1 corrisponde alla seconda riga del file CSV ed 
# ha indice 0 nel DataFrame.
x = df_csv.iloc[0:1, 0:1]
print(x,'\n')
print(x.values[0][0],'\n')

y = df_csv.iloc[1, 1]
print(y,'\n')


# Vediamo informazioni generali sulla struttura (tipi di dati e valori nulli)
print("Informazioni generali sul DataFrame:")
df_csv.info()

Prime n righe del dataset:

      Col1  Col2    Col3
0  1.50000   2.0  3.1089
1  4.20178   5.5  6.0000
2  5.00000   6.0  7.2000

   Col2
1   5.5

   Col1
0   1.5

1.5

5.5

Informazioni generali sul DataFrame:
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Col1    3 non-null      float64
 1   Col2    3 non-null      float64
 2   Col3    3 non-null      float64
dtypes: float64(3)
memory usage: 204.0 bytes

add new row

In [31]:
import pandas as pd

# Carichiamo il file CSV presente nella cartella del progetto
df_csv = pd.read_csv('dati.csv', sep=';')

# 1. Definiamo la nuova riga come un piccolo DataFrame (con le stesse colonne)
nuova_riga = pd.DataFrame([{'Col1': -2, 'Col2': 1.5, 'Col3': 30}])

# 2. Concateniamo il vecchio DataFrame con la nuova riga
# ignore_index=True serve a rinumerare correttamente le righe in sequenza (0, 1, 2, 3...)
df_csv = pd.concat([df_csv, nueva_riga] if 'nueva_riga' in locals() else [df_csv, nuova_riga], ignore_index=True)

# Semplificato:
df_csv = pd.concat([df_csv, nuova_riga*2], ignore_index=True)

# 3. Vediamo il risultato aggiornato
display(df_csv.tail())  # .tail() mostra le ultime righe

df_csv.to_csv('dati2.csv', sep=';', index=False)
df_csv.to_csv('dati3.csv', sep=';', index=True)

print("File salvato con successo!")

      Col1  Col2     Col3
0  1.50000   2.0   3.1089
1  4.20178   5.5   6.0000
2  5.00000   6.0   7.2000
3 -2.00000   1.5  30.0000
4 -4.00000   3.0  60.0000

File salvato con successo!

OOP for program with CVS and pandas

In [ ]:
import pandas as pd

class DatasetManager:
    """Classe orientata agli oggetti per caricare, modificare e salvare dataset."""
    
    def __init__(self, filepath, sep=';'):
        self.filepath = filepath
        self.sep = sep
        self.df = None
        
    def load_data(self):
        """Carica il file CSV in un DataFrame."""
        self.df = pd.read_csv(self.filepath, sep=self.sep)
        print(f"Dataset '{self.filepath}' caricato correttamente.")
        
    def add_row(self, row_data):
        """Aggiunge una nuova riga passando un dizionario."""
        nuova_riga = pd.DataFrame([row_data])
        self.df = pd.concat([self.df, nuova_riga], ignore_index=True)
        print("Nuova riga aggiunta con successo.")
        
    def show_tail(self, n=5):
        """Mostra le ultime righe del DataFrame."""
        display(self.df.tail(n))
        
    def save_data(self, output_path, include_index=False):
        """Salva il DataFrame modificato su un nuovo file CSV."""
        self.df.to_csv(output_path, sep=self.sep, index=include_index)
        print(f"File salvato con successo come '{output_path}'.")

# ==========================================
# Utilizzo pratico della classe
# ==========================================

# 1. Istanziamo l'oggetto
manager = DatasetManager('dati.csv', sep=';')

# 2. Carichiamo i dati
manager.load_data()

# 3. Aggiungiamo una riga usando un dizionario
manager.add_row({'Col1': -2.0, 'Col2': 1.5, 'Col3': 30.0})

# 4. Visualizziamo la fine del DataFrame
manager.show_tail()


# 5. Salviamo il nuovo file
manager.save_data('dati_oop_output.csv', include_index=False)

Dataset 'dati.csv' caricato correttamente.
Nuova riga aggiunta con successo.

      Col1  Col2     Col3
0  1.50000   2.0   3.1089
1  4.20178   5.5   6.0000
2  5.00000   6.0   7.2000
3 -2.00000   1.5  30.0000

File salvato con successo come 'dati_oop_output.csv'.